.TH "C:/Users/Wojtek/Documents/C/PP2/projektpp2/baza_kontaktow/add_and_remove_elements.c" 3 "Pn, 30 maj 2016" "Version 1.0" "Baza_Kontaktów" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Wojtek/Documents/C/PP2/projektpp2/baza_kontaktow/add_and_remove_elements.c \- Przechowuje funkcje do tworzenia list, usuwania list, dodawania elementów i usuwania elementów\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'baza_kontaktow\&.h'\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "struct \fBtelephone_nr\fP * \fBCreatePhoneList\fP (struct \fBtelephone_nr\fP *FrontTelList)"
.br
.RI "\fIFunkcja tworzy listę \fBtelephone_nr\fP i dodaje do niej pierwszy element\&. \fP"
.ti -1c
.RI "struct \fBtelephone_nr\fP * \fBInsertTelNum\fP (struct \fBtelephone_nr\fP *FrontTelList)"
.br
.RI "\fIFunkcja dodaje nowy element na koniec listy\&. \fP"
.ti -1c
.RI "struct \fBemail_node\fP * \fBCreateEmalList\fP (struct \fBemail_node\fP *FrontEmailList)"
.br
.RI "\fIFunkcja tworzy listę \fBemail_node\fP i dodaje do niej pierwszy element\&. \fP"
.ti -1c
.RI "struct \fBemail_node\fP * \fBInsertEmail\fP (struct \fBemail_node\fP *FrontEmailList)"
.br
.RI "\fIFunkcja dodaje nowy element na koniec listy\&. \fP"
.ti -1c
.RI "struct \fBUser_Node\fP * \fBcreate_list\fP (struct \fBUser_Node\fP *FrontUserList)"
.br
.RI "\fIFunkcja tworzy listę \fBUser_Node\fP i dodaje do niej pierwszy element\&. \fP"
.ti -1c
.RI "struct \fBUser_Node\fP * \fBInsertUser\fP (struct \fBUser_Node\fP *FrontUserList)"
.br
.RI "\fIFunkcja dodaje nowy element na koniec listy\&. \fP"
.ti -1c
.RI "struct \fBUser_Node\fP * \fBDeleteUserNode\fP (struct \fBUser_Node\fP *FrontUserList, int data)"
.br
.RI "\fIFunkcja usuwa użytkownika o podanym ID\&. \fP"
.ti -1c
.RI "struct \fBemail_node\fP * \fBDeleteEmailNode\fP (struct \fBemail_node\fP *FrontEmailList, int data)"
.br
.RI "\fIFunkcja usuwa emaile o podanym ID\&. \fP"
.ti -1c
.RI "struct \fBtelephone_nr\fP * \fBDeleteTelNode\fP (struct \fBtelephone_nr\fP *FrontTelList, int data)"
.br
.RI "\fIFunkcja usuwa numery telefonów o podanym ID\&. \fP"
.ti -1c
.RI "void \fBremove_list\fP (struct \fBUser_Node\fP **temp)"
.br
.RI "\fIProcedura usuwa liste typu \fBUser_Node\fP\&. \fP"
.ti -1c
.RI "void \fBremove_tel_list\fP (struct \fBtelephone_nr\fP **temp)"
.br
.RI "\fIProcedura usuwa liste typu \fBtelephone_nr\fP\&. \fP"
.ti -1c
.RI "void \fBremove_email_list\fP (struct \fBemail_node\fP **temp)"
.br
.RI "\fIProcedura usuwa liste typu \fBemail_node\fP\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Przechowuje funkcje do tworzenia list, usuwania list, dodawania elementów i usuwania elementów\&. 


.SH "Dokumentacja funkcji"
.PP 
.SS "struct \fBUser_Node\fP * create_list (struct \fBUser_Node\fP * FrontUserList)"

.PP
Funkcja tworzy listę \fBUser_Node\fP i dodaje do niej pierwszy element\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontUserList\fP wskaźnik na początek listy 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontUserList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBemail_node\fP * CreateEmalList (struct \fBemail_node\fP * email_node)"

.PP
Funkcja tworzy listę \fBemail_node\fP i dodaje do niej pierwszy element\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontEmailList\fP wskaźnik na początek listy 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontEmailList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBtelephone_nr\fP * CreatePhoneList (struct \fBtelephone_nr\fP * FrontTelList)"

.PP
Funkcja tworzy listę \fBtelephone_nr\fP i dodaje do niej pierwszy element\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontTelList\fP wskaźnik na początek listy\&. 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontTelList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBemail_node\fP * DeleteEmailNode (struct \fBemail_node\fP * FrontEmailList, int data)"

.PP
Funkcja usuwa emaile o podanym ID\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontEmailList\fP wskaźnik na początek listy\&. 
.br
\fIdata\fP przechowuje ID podane przez użytkownika 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontEmailList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBtelephone_nr\fP * DeleteTelNode (struct \fBtelephone_nr\fP * FrontTelList, int data)"

.PP
Funkcja usuwa numery telefonów o podanym ID\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontTelList\fP wskaźnik na początek listy\&. 
.br
\fIdata\fP przechowuje ID podane przez użytkownika 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontTelList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBUser_Node\fP * DeleteUserNode (struct \fBUser_Node\fP * FrontUserList, int data)"

.PP
Funkcja usuwa użytkownika o podanym ID\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontUserList\fP wskaźnik na początek listy\&. 
.br
\fIdata\fP przechowuje ID podane przez użytkownika 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontUserList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBemail_node\fP * InsertEmail (struct \fBemail_node\fP * FrontEmailList)"

.PP
Funkcja dodaje nowy element na koniec listy\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontEmailList\fP wskaźnik na początek listy\&. 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontEmailList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBtelephone_nr\fP * InsertTelNum (struct \fBtelephone_nr\fP * FrontTelList)"

.PP
Funkcja dodaje nowy element na koniec listy\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontTelList\fP wskaźnik na początek listy\&. 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontTelList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "struct \fBUser_Node\fP * InsertUser (struct \fBUser_Node\fP * FrontUserList)"

.PP
Funkcja dodaje nowy element na koniec listy\&. 
.PP
\fBParametry:\fP
.RS 4
\fIFrontUserList\fP wskaźnik na początek listy\&. 
.RE
.PP
\fBZwraca:\fP
.RS 4
FrontUserList zwraca wskażnik na pierwszy element 
.RE
.PP

.SS "void remove_email_list (struct \fBemail_node\fP ** temp)"

.PP
Procedura usuwa liste typu \fBemail_node\fP\&. 
.PP
\fBParametry:\fP
.RS 4
\fItemp\fP podwójny wskaźnik na początek listy \&. 
.RE
.PP

.SS "void remove_list (struct \fBUser_Node\fP ** temp)"

.PP
Procedura usuwa liste typu \fBUser_Node\fP\&. 
.PP
\fBParametry:\fP
.RS 4
\fItemp\fP podwójny wskaźnik na początek listy\&. 
.RE
.PP

.SS "void remove_tel_list (struct \fBtelephone_nr\fP ** temp)"

.PP
Procedura usuwa liste typu \fBtelephone_nr\fP\&. 
.PP
\fBParametry:\fP
.RS 4
\fItemp\fP podwójny wskaźnik na początek listy\&. 
.RE
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Baza_Kontaktów\&.
