.TH "Dokumentacja katalogu C:/Users/Wojtek/Documents/C/PP2/projektpp2/baza_kontaktow" 3 "Pn, 30 maj 2016" "Version 1.0" "Baza_Kontakt贸w" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu C:/Users/Wojtek/Documents/C/PP2/projektpp2/baza_kontaktow \- 
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBadd_and_remove_elements\&.c\fP"
.br
.RI "\fIPrzechowuje funkcje do tworzenia list, usuwania list, dodawania element贸w i usuwania element贸w\&. \fP"
.ti -1c
.RI "plik \fBbaza_kontaktow\&.h\fP"
.br
.RI "\fIPrzechowuje struktury i nagl體ki funkcji\&. \fP"
.ti -1c
.RI "plik \fBmain\&.c\fP"
.br
.RI "\fIG艂贸wna funcka programu\&. \fP"
.ti -1c
.RI "plik \fBoperations_on_lists\&.c\fP"
.br
.RI "\fIPrzechowuje definicje funkcji do obs艂ugi list oraz funkcji og贸lnego uzytku\&. \fP"
.ti -1c
.RI "plik \fBread_and_save_to_file\&.c\fP"
.br
.RI "\fIPrzechowuje funkcje do odczytu i zapisu plik贸w\&. \fP"
.ti -1c
.RI "plik \fBsort_list\&.c\fP"
.br
.RI "\fIPrzechowuje funkcje do sortowania list\&. \fP"
.in -1c
