.TH "email_node" 3 "Pn, 30 maj 2016" "Version 1.0" "Baza_Kontaktów" \" -*- nroff -*-
.ad l
.nh
.SH NAME
email_node \- Struktura przechowuje adresy email uzytkownika i wskaznik na nastepny element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <baza_kontaktow\&.h>\fP
.SS "Pola danych"

.in +1c
.ti -1c
.RI "unsigned int \fBID_email\fP"
.br
.ti -1c
.RI "char \fBem\fP [40]"
.br
.ti -1c
.RI "struct \fBemail_node\fP * \fBnext\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Struktura przechowuje adresy email uzytkownika i wskaznik na nastepny element\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Baza_Kontaktów\&.
