.TH "telephone_nr" 3 "Pn, 30 maj 2016" "Version 1.0" "Baza_Kontakt贸w" \" -*- nroff -*-
.ad l
.nh
.SH NAME
telephone_nr \- Struktura przechowuje numery telefon體 uzytkownika i wskaznik na nastepny element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <baza_kontaktow\&.h>\fP
.SS "Pola danych"

.in +1c
.ti -1c
.RI "unsigned int \fBID_tel\fP"
.br
.ti -1c
.RI "unsigned long int \fBtel_nr\fP"
.br
.ti -1c
.RI "struct \fBtelephone_nr\fP * \fBnext\fP"
.br
.in -1c
.SH "Opis szczeg贸艂owy"
.PP 
Struktura przechowuje numery telefon體 uzytkownika i wskaznik na nastepny element\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu 藕r贸d艂owego programem Doxygen dla Baza_Kontakt贸w\&.
