.TH "User_Node" 3 "Pn, 30 maj 2016" "Version 1.0" "Baza_Kontaktów" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User_Node \- Struktura przechowuje dane uzytkownika i wskaznik na nastepny element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <baza_kontaktow\&.h>\fP
.SS "Pola danych"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "char \fBname\fP [15]"
.br
.ti -1c
.RI "char \fBsurname\fP [20]"
.br
.ti -1c
.RI "char \fBcity\fP [40]"
.br
.ti -1c
.RI "char \fBstreet\fP [40]"
.br
.ti -1c
.RI "unsigned int \fBhouse_number\fP"
.br
.ti -1c
.RI "char \fBpostal_code\fP [8]"
.br
.ti -1c
.RI "char \fBpost_office\fP [30]"
.br
.ti -1c
.RI "struct \fBUser_Node\fP * \fBnext\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Struktura przechowuje dane uzytkownika i wskaznik na nastepny element\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Baza_Kontaktów\&.
